name: Build and Push Docker Image
on:
  push:
    branches: ["main"]  # 触发分支

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # 授权写入 GitHub Packages
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      # 2. 登录镜像仓库（以 GitHub Packages 为例）
      # - name: Login to GHCR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GHCR_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get next patch version
        id: semver
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: 2.2.1  # 基于最新标签生成下一版本
      # 3. 构建并推送镜像
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nfs-server-alpine:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nfs-server-alpine:${{ steps.semver.outputs.patch }}
            # ghcr.io/${{ github.repository_owner }}/my-image:latest
            # ghcr.io/${{ github.repository_owner }}/my-image:${{ github.sha }}